### ISSUE TITLE
Build fails on MacBook Air M1

### ISSUE THREAD

**Issue by agniho3a** [Slackadays/Clipboard#24] opened 2022-12-27 17:55 UTC
System Information:
> MacBook Air  M1, 2020
Chip: Apple M1
Memory: 16 GB
macOS: 13.1 (22C65)

Getting errors during 'build'. Please see the logs below:

```
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:50:6: error: no type named 'jthread' in namespace 'std'; did you mean 'thread'?
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:189:19: error: no member named 'request_stop' in 'std::thread'
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:437:26: error: no type named 'stop_token' in namespace 'std'
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:513:23: error: no member named 'request_stop' in 'std::thread'
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:647:35: error: no member named 'request_stop' in 'std::thread'
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:649:42: error: no member named 'jthread' in namespace 'std'
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:794:26: error: no member named 'jthread' in namespace 'std'
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:806:19: error: no member named 'request_stop' in 'std::thread'
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:819:19: error: no member named 'request_stop' in 'std::thread'
In file included from /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:3:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:477:12: note: in instantiation of function template specialization 'std::condition_variable::wait_until<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>, (lambda at /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:447:62)>' requested here
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:447:16: note: in instantiation of function template specialization 'std::condition_variable::wait_for<long long, std::ratio<1, 1000>, (lambda at /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:447:62)>' requested here
In file included from /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:3:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:477:12: note: in instantiation of function template specialization 'std::condition_variable::wait_until<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>, (lambda at /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:453:62)>' requested here
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:453:16: note: in instantiation of function template specialization 'std::condition_variable::wait_for<long long, std::ratio<1, 1000>, (lambda at /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:453:62)>' requested here
In file included from /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:3:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:477:12: note: in instantiation of function template specialization 'std::condition_variable::wait_until<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>, (lambda at /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:469:62)>' requested here
/Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:469:16: note: in instantiation of function template specialization 'std::condition_variable::wait_for<long long, std::ratio<1, 1000>, (lambda at /Users/UZER01/tools/cb/Clipboard/src/clipboard.cpp:469:62)>' requested here

**Comment by Slackadays** [comment] 2022-12-27 17:56
Dupe of #20, #21, and #22: install GCC 11/12 to get C++20 compatibility

**Closed by Slackadays** 2022-12-27 17:56 UTC
