### ISSUE TITLE
Screen flickering with Hyprland

### ISSUE THREAD

**Issue by glyh** [Slackadays/Clipboard#194] opened 2024-06-02 06:31 UTC
**Describe the bug**

Once I run `cb` with no argument once, all my windows start to dance.

**To Reproduce**
1. Install `hyprland-git` on Arch Linux
3. Run `cb`

**Expected behavior**
Windows doesn't dance. 

**Screenshots**

**Version**
The version of CB you're using, how you got it, and what system you're using.
0.9.0 AUR

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [x] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [x] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [x] I'm using the latest commit/release (we only support the latest)
- [x] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**

**Before you post**
Please make sure you check previous bug reports before filing a new one.
This will help keep the Issues section less cluttered. :)
Feel free to delete this section once you've completed this form.

**Comment by Darukutsu** [comment] 2024-06-26 13:54
same goes for river

**Comment by Slackadays** [comment] 2024-07-31 20:49
Dupe of #171, there is currently no fix other than to use a different WM or disable Wayland or add support for a specific protocol :(

**Closed by Slackadays** 2024-07-31 20:49 UTC
Labels: bug
