### ISSUE TITLE
Breaks my Ubuntu setup

### ISSUE THREAD

**Issue by gabriel-grinspan** [Slackadays/Clipboard#184] opened 2024-01-02 17:21 UTC
**Describe the bug**
I installed the app and I immediately found my Gnome instance flickering between windows. Even after uninstalling, the issue persisted. I had to manually pkill.

**To Reproduce**
1. Install app
2. Open app
3. Attempt to use app.
4. Failure
5. Uninstall
6. Continued failure

**Expected behavior**
The program doesn't bork my machine.

**Screenshots**
I didn't record a video, and I will not be reinstalling.

**Version**
Latest Faltpak

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [ ] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [ ] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [x] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [x] I'm using the latest commit/release (we only support the latest)
- [ ] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**

**Before you post**
Please make sure you check previous bug reports before filing a new one.
This will help keep the Issues section less cluttered. :)
Feel free to delete this section once you've completed this form.

**Comment by Slackadays** [comment] 2024-01-02 17:22
Duplicate of #171

**Closed by Slackadays** 2024-01-02 17:22 UTC
Labels: bug
