### ISSUE TITLE
cb cut does not remove the clipboard entry on windows

### ISSUE THREAD

**Issue by gkruschina** [Slackadays/Clipboard#173] opened 2023-10-21 09:02 UTC
cb cut "AVeryStrongPassword!"
cb | some-program

The clipboard-entry "AveryStrongPassowrd" is still in the clipboard.

**Comment by iFreilicht** [comment] 2024-09-25 22:59
Can confirm, this is the case on macOS as well. On Linux it works as intended.

```
$ cb cut "secure password donut steel"
 ✔  Cut text "secure password donut steel"                                                                                                            
$ cb paste
 ✔  Pasted one item                                                                                                                                   
$ cb paste
┃ There is currently nothing in the clipboard.                                                                                                        
┃ Add cut, copy, or paste to the end, like cb copy to get started, or if you need help, try cb -h to show the help screen.
```

**Comment by Slackadays** [comment] 2024-10-19 00:46
Fixed in https://github.com/Slackadays/Clipboard/commit/0fef41a02db4f21ef07417b3d02c823017daaa33

@eitamal @ydx-2147483647

**Closed by Slackadays** 2024-10-19 00:46 UTC
Labels: bug
