### ISSUE TITLE
Bug: Errors while running cmake build on macOS

### ISSUE THREAD

**Issue by ashwinkumar01** [Slackadays/Clipboard#21] opened 2022-12-27 12:48 UTC
**Describe the bug**
Running cmake build (with or without sudo) produces a list of errors on macOS 12.6.1 Monterey

**Additional context**
`/Users/<user>/personal/Clipboard/src/clipboard.cpp:51:6: error: no type named 'jthread' in namespace 'std'; did you mean 'thread'?
std::jthread indicator;
~~~~~^~~~~~~
     thread
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/thread:220:24: note: 'thread' declared here
class _LIBCPP_TYPE_VIS thread
                       ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:182:19: error: no member named 'request_stop' in 'std::thread'
        indicator.request_stop();
        ~~~~~~~~~ ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:432:26: error: no type named 'stop_token' in namespace 'std'
void setupIndicator(std::stop_token st) {
                    ~~~~~^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:503:23: error: no member named 'request_stop' in 'std::thread'
            indicator.request_stop();
            ~~~~~~~~~ ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:637:35: error: no member named 'request_stop' in 'std::thread'
                        indicator.request_stop();
                        ~~~~~~~~~ ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:639:42: error: no member named 'jthread' in namespace 'std'
                        indicator = std::jthread(setupIndicator);
                                    ~~~~~^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:778:26: error: no member named 'jthread' in namespace 'std'
        indicator = std::jthread(setupIndicator);
                    ~~~~~^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:786:19: error: no member named 'request_stop' in 'std::thread'
        indicator.request_stop();
        ~~~~~~~~~ ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:799:19: error: no member named 'request_stop' in 'std::thread'
        indicator.request_stop();
        ~~~~~~~~~ ^
In file included from /Users/<user>/personal/Clipboard/src/clipboard.cpp:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/filesystem:251:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/locale:192:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__locale:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/mutex:190:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:431:12: error: invalid argument type 'void' to unary expression
    while (!__pred())
           ^~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:477:12: note: in instantiation of function template specialization 'std::condition_variable::wait_until<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>, (lambda at /Users/<user>/personal/Clipboard/src/clipboard.cpp:442:62)>' requested here
    return wait_until(__lk, chrono::steady_clock::now() + __d,
           ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:442:16: note: in instantiation of function template specialization 'std::condition_variable::wait_for<long long, std::ratio<1, 1000>, (lambda at /Users/<user>/personal/Clipboard/src/clipboard.cpp:442:62)>' requested here
            cv.wait_for(lock, std::chrono::milliseconds(50), [&]{ return st.stop_requested(); });
               ^
In file included from /Users/<user>/personal/Clipboard/src/clipboard.cpp:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/filesystem:251:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/locale:192:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__locale:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/mutex:190:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:431:12: error: invalid argument type 'void' to unary expression
    while (!__pred())
           ^~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:477:12: note: in instantiation of function template specialization 'std::condition_variable::wait_until<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>, (lambda at /Users/<user>/personal/Clipboard/src/clipboard.cpp:448:62)>' requested here
    return wait_until(__lk, chrono::steady_clock::now() + __d,
           ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:448:16: note: in instantiation of function template specialization 'std::condition_variable::wait_for<long long, std::ratio<1, 1000>, (lambda at /Users/<user>/personal/Clipboard/src/clipboard.cpp:448:62)>' requested here
            cv.wait_for(lock, std::chrono::milliseconds(50), [&]{ return st.stop_requested(); });
               ^
In file included from /Users/<user>/personal/Clipboard/src/clipboard.cpp:3:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/filesystem:251:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/locale:192:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__locale:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/mutex:190:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:431:12: error: invalid argument type 'void' to unary expression
    while (!__pred())
           ^~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/__mutex_base:477:12: note: in instantiation of function template specialization 'std::condition_variable::wait_until<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000>>, (lambda at /Users/<user>/personal/Clipboard/src/clipboard.cpp:464:62)>' requested here
    return wait_until(__lk, chrono::steady_clock::now() + __d,
           ^
/Users/<user>/personal/Clipboard/src/clipboard.cpp:464:16: note: in instantiation of function template specialization 'std::condition_variable::wait_for<long long, std::ratio<1, 1000>, (lambda at /Users/<user>/personal/Clipboard/src/clipboard.cpp:464:62)>' requested here
            cv.wait_for(lock, std::chrono::milliseconds(50), [&]{ return st.stop_requested(); });
               ^
12 errors generated.
make[2]: *** [CMakeFiles/clipboard.dir/src/clipboard.cpp.o] Error 1
make[1]: *** [CMakeFiles/clipboard.dir/all] Error 2`

**Comment by Slackadays** [comment] 2022-12-27 12:51
Dupe of https://github.com/Slackadays/Clipboard/issues/20, the fix is to install GCC 11/12. libc++ (Clang) currently does not support most C++20 features, but GCC 11/12 does.

**Closed by Slackadays** 2022-12-27 12:51 UTC
