### ISSUE TITLE
is cannot show two info , let me show

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#144] opened 2023-07-09 12:38 UTC
i set 'ls' command, this is :
![image](https://github.com/Slackadays/Clipboard/assets/87791643/791d124e-43a3-4fbf-b5cc-6ca3277a4b6b)

so ,when i copy first copy info, is 'Application' string:
![image](https://github.com/Slackadays/Clipboard/assets/87791643/141068f8-a0cf-4e84-9f34-36dea50ad4c3)

and i copy second info is 'Desktop' string:
![image](https://github.com/Slackadays/Clipboard/assets/87791643/d39b9e13-b010-4226-9eb0-0a721d661f36)

show i enter cb hs, it just show last copy info , just 'Desktop' ,not  'Application' .
![image](https://github.com/Slackadays/Clipboard/assets/87791643/9cdfd22d-9aae-45ca-9e36-e6ed28b1a3fa)

**Comment by newyorkthink** [comment] 2023-07-09 12:40
i want to , i copy , copy ,copy more ,and i when to us cb, it can show info to my recently copy

**Comment by Slackadays** [comment] 2023-07-09 20:56
![Screenshot from 2023-07-09 16-56-04](https://github.com/Slackadays/Clipboard/assets/69403549/1a32d910-9d1f-41ce-b1be-d59dfbc6c49b)

did you copy this before?

**Comment by newyorkthink** [comment] 2023-07-09 23:22
> ![Screenshot from 2023-07-09 16-56-04](https://user-images.githubusercontent.com/69403549/252168771-1a32d910-9d1f-41ce-b1be-d59dfbc6c49b.png)
> 
> did you copy this before?

No

**Comment by newyorkthink** [comment] 2023-07-10 01:15
i test browser, or terminal , is always

**Comment by newyorkthink** [comment] 2023-07-11 00:37
now , i just test again , i show you ,juet last one.
or you fix:

for example:
![image](https://github.com/Slackadays/Clipboard/assets/87791643/3edee074-12d9-488a-b5dc-19bdd05b8635)
i copy you comment.

![image](https://github.com/Slackadays/Clipboard/assets/87791643/f71693ec-600e-4f52-873f-a8363e7d9eee)
xclip it show you comment

when i copy the translate:
![image](https://github.com/Slackadays/Clipboard/assets/87791643/1b44ab43-ce70-4682-b228-0af0020baf35)
xclip can get it.

but your cb command ,just get the last comment:
![image](https://github.com/Slackadays/Clipboard/assets/87791643/a8525f9b-b1de-4dc8-8777-3e27c4661a5b)

**Comment by Slackadays** [comment] 2023-07-11 02:38
then, this is a duplicate of #139, because `cb` does not update itself in the background, but rather only when you use the `cb` command. 

if you copy something once, then copy another thing, then `cb` will only see the second thing unless you monitor the clipboard in the background with a script: https://flathub.org/apps/app.getclipboard.Clipboard

**Comment by newyorkthink** [comment] 2023-07-11 03:03
> then, this is a duplicate of #139, because `cb` does not update itself in the background, but rather only when you use the `cb` command.然后，这是 #139 的副本，因为 `cb` 不会在后台更新自身，而是仅在您使用 `cb` 命令时更新。
> 
> if you copy something once, then copy another thing, then `cb` will only see the second thing unless you monitor the clipboard in the background with a script: https://flathub.org/apps/app.getclipboard.Clipboard如果您复制一次内容，然后复制另一内容，则 `cb` 将只能看到第二件事，除非您使用脚本在后台监视剪贴板： https://flathub.org/apps/app.getclipboard.Clipboard

i suggest , can you make a service, to run background

**Comment by newyorkthink** [comment] 2023-07-11 03:07
look like this

#!/bin/bash

# 初始化剪贴板内容
clipboard=$(xclip -selection clipboard -o)

while true; do
    # 检查剪贴板内容是否发生变化
    new_clipboard=$(xclip -selection clipboard -o)

    if [ "$new_clipboard" != "$clipboard" ]; then
        # 如果剪贴板内容发生变化，执行你的命令
        echo "$new_clipboard" | cb copy
        clipboard=$new_clipboard
    fi

    # 等待一段时间再次检查
    sleep 1
done


but you can better

**Comment by Slackadays** [comment] 2023-07-11 03:09
you can do this:

```sh
sh -c "while true; do cb; sleep 2; done"
```

then, make that a service, and then you are done

**Comment by newyorkthink** [comment] 2023-07-11 03:17
![image](https://github.com/Slackadays/Clipboard/assets/87791643/1c62040b-31fb-4c20-a587-643e705cfa86)

i run you command , my system is break.

i must restart os

**Comment by Slackadays** [comment] 2023-07-11 03:18
:eyes:

**Comment by Slackadays** [comment] 2023-09-30 01:59
Added in https://github.com/Slackadays/Clipboard/commit/95ddeadc453a4b707cb57afdeb15880c0bf774ed

**Closed by Slackadays** 2023-09-30 01:59 UTC
Labels: enhancement
