### ISSUE TITLE
Bug: Installation on M1 Mac doesn't work

### ISSUE THREAD

**Issue by xdssio** [Slackadays/Clipboard#22] opened 2022-12-27 13:17 UTC
**Describe the bug**
Error when building on M1 mac.

**To Reproduce**
I errors on `make --build .`

**Expected behavior**

```
p:464:16: note: in instantiation of function template specialization 'std::condition_variable::wait_for<long long, std::ratio<1, 1000>, (lambda at /Users/yonatanalexander/development/misc_projects/tmp/Clipboard/src/clipboard.cpp:464:62)>' requested here
            cv.wait_for(lock, std::chrono::milliseconds(50), [&]{ return st.stop_requested(); });
               ^
12 errors generated.
make[2]: *** [CMakeFiles/clipboard.dir/src/clipboard.cpp.o] Error 1
make[1]: *** [CMakeFiles/clipboard.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Slackadays** [comment] 2022-12-27 13:17
What are your complete logs?

**Comment by Slackadays** [comment] 2022-12-27 13:20
Dupe of #20 and #21, install GCC 11/12.

**Closed by Slackadays** 2022-12-27 13:20 UTC
