### ISSUE TITLE
After installing using the suggested tool GLIBCXX_3.4.29 is not found

### ISSUE THREAD

**Issue by TenoTrash** [Slackadays/Clipboard#84] opened 2023-02-16 15:30 UTC
**Describe the bug**
After installing using the suggeted methond:
curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh | sh

**To Reproduce**
❯ curl -sSL https://github.com/Slackadays/Clipboard/raw/main/src/install.sh | sh
Archive:  clipboard-linux.zip
   creating: bin/
   creating: lib/
  inflating: bin/clipboard           
  inflating: lib/libclipboardwayland.so  
  inflating: lib/libclipboardx11.so  
  inflating: lib/libgui.a            
Clipboard installed successfully!                                                                                      

❯ cb
cb: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by cb)
cb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by cb)
cb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by cb)

I was usin Linux Mint Debian Edition 5 (Debian 11)

**Comment by Slackadays** [comment] 2023-02-16 15:33
Dupe of #50, either compile Clipboard manually or upgrade your OS.

**Closed by Slackadays** 2023-02-16 15:33 UTC
Labels: bug
