### ISSUE TITLE
CB memory leaks and consumes all RAM  on system

### ISSUE THREAD

**Issue by jscarrott** [Slackadays/Clipboard#179] opened 2023-12-05 10:14 UTC
**Describe the bug**
I use CB heavily however over time it seems it can get into a state where each CB instance is using gigabytes of RAM to the point where my system becomes unresponsive. Memory use seems to increase without anything being copied.

**To Reproduce**
Setup CB to sync the clipboard and just be in use regularly

**Expected behavior**
Memory use doesn't creep up over time

**Screenshots**

Snapshot of cb processes shortly after killing all processes: 
![image](https://github.com/Slackadays/Clipboard/assets/1215953/04c7de5d-ef9f-46c8-a337-fcaa1ea86ee6)

Snapshot 5 minutes later with little to no copying: 
![image](https://github.com/Slackadays/Clipboard/assets/1215953/a6fa8b29-5625-40ff-a813-19135a4984d4)

**Version**
0.8.2 ubuntu 23.10

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [ ] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [ ] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ X] I think bachata is the best music
- [X ] I'm using the latest commit/release (we only support the latest)
- [ ] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**

**Before you post**
Please make sure you check previous bug reports before filing a new one.
This will help keep the Issues section less cluttered. :)
Feel free to delete this section once you've completed this form.

**Comment by Slackadays** [comment] 2023-12-05 16:20
This has to be a bug with daemon detection as there should only be one background cb instance

**Comment by jscarrott** [comment] 2023-12-05 17:05
If there is any debug information you need I'm happy to try and collect that for you. I will also say that there are a large number of defunct cb processes that seem to linger for a long time as well.

**Comment by Slackadays** [comment] 2023-12-05 17:29
Is it possible for you to upgrade to 0.8.3? I believe it actually addressed this specific issue: https://github.com/Slackadays/Clipboard/releases/tag/0.8.3

**Comment by jscarrott** [comment] 2023-12-05 21:17
I'm actually on 0.8.3 it looks like it also has a bug where the version is reported as 0.8.2 (commit c785b5e). I had updated through linuxbrew and just run the binary directly from the release you linked and they both say 0.8.2

**Comment by Slackadays** [comment] 2023-12-06 00:38
I'm going to check out the daemon detector and see if I can reproduce this. Also, how many entries do your clipboards have? I'm wondering because you mentioned that you use CB heavily and I have no idea how many entries CB's power users are saving.

**Comment by willothy** [comment] 2023-12-07 17:03
Definitely has nothing to do with the number of entries, I just started using `cb` a few hours ago and I have run into this issue when attempting to set it up as a clipboard provider for Neovim.

**Comment by Slackadays** [comment] 2023-12-14 00:28
@jscarrott @willothy Would you mind trying out the following command as a temporary workaround?

```sh
alias cb="killall -q cb; cb"
```

What this does is automatically get rid of all existing `cb` processes before invoking `cb`, so that there will only ever be one instance running. The reason we don't already do this is because there could be `cb` running by a different user or in a script. Therefore, we can't guarantee this method will always give the expected result, but for this particular case, it should work just fine.

**Comment by willothy** [comment] 2023-12-14 00:34
Yes, that's what I ended up doing temporarily. It helped but I ended up switching back to xsel for now. Cb is awesome except for this though, definitely will switch back once it's fixed :)

On that note, couldn't some kind of lockfile/pidfile be created in the users' `/var/run` dirs or equivalent to check for this?

**Comment by Slackadays** [comment] 2023-12-14 02:48
Fixed in https://github.com/Slackadays/Clipboard/commit/bc528a66c225c4be1434184c893ba3cf729f32e2

**Closed by Slackadays** 2023-12-14 02:48 UTC
Labels: bug

**Comment by willothy** [comment] 2023-12-14 02:52
Oh awesome, thanks! That was quick lol

**Comment by Slackadays** [comment] 2023-12-14 03:06
I hate `xsel` and `xclip` and `wl-clipboard` (which is why I made `cb`), so I'll do my best to make sure nobody has to use them. :)

**Comment by jscarrott** [comment] 2023-12-14 10:50
Brilliant! Is there a timescale for when this will make it into a release, so I can stop periodically killing cb instances?

**Comment by Slackadays** [comment] 2023-12-17 15:58
@jscarrott 0.9.0 is out now: https://github.com/Slackadays/Clipboard/releases/tag/0.9.0
