### ISSUE TITLE
Clips not loaded to standard clipboard through script invoked with shortcut

### ISSUE THREAD

**Issue by chromevanadium** [Slackadays/Clipboard#148] opened 2023-07-13 10:01 UTC
**Describe the bug**
Clips are not correctly loaded to the standard clipboard when a script is triggered through a shortcut key. They are correctly loaded, however, when running the same script from the terminal.

**To Reproduce**

1. Create a permanent variable: `cb add_c01 "Clip01"`
2. Create a script `~/.local/bin/testscript` with contents:
    ```
    #!/bin/bash
    echo "Standard clipboard: $(cb paste)" > ~/debug.txt
    echo "Clip c1:            $(cb paste_c01)" >> ~/debug.txt
    echo "Now moving permanent clipboard to standard clipboard" >> ~/debug.txt
    cb load_c01
    echo "Standard clipboard: $(cb paste)" >> ~/debug.txt
    ```
3. Copy some text to the clipboard (i.e. highlight, hit Ctrl+C).
4. Run the script. See the output in `cat ~/debug.txt`. First line correctly shows what you copied in step 3, last line shows that the standard clipboard was correctly updated with permanent clip _c1. Verify: a paste (Ctrl+V) now yields the contents of the permanent clip.
5. Now assign that script to a shortcut key through the functionality of your desktop environment or window manager.
6. Again copy some text to the clipboard
7. Now run the script by pressing the shortcut key you assigned in step 5. This time, the standard clipboard was not updated with the contents of the permanent clip (verify in the output of `~/debug.txt` and by pasting.

**Expected behavior**
The application should correctly a clip to the standard clipboard both when running a script from the terminal *and* when running the script from a keyboard shortcut (likely, the same issue will happen when launching from a desktop launcher).

**Screenshots**
NA

**Version**
CB 0.8.1 from Flathub
* on Fedora 38 with Gnome 44.2 on Wayland
* on Fedora 38 with Gnome 44.2 on Xorg
* on Fedora 38 with Xcfe desktop (in a VM)

CB 0.8.1 from Snap
* on  Ubuntu 22.04 with Gnome Shell on Wayland (in a VM.

CB CB 0.8.1 from AUR
* On EndeavourOS Cassini Nova

**Comment by Slackadays** [comment] 2023-07-13 16:42
done, fixed in https://github.com/Slackadays/Clipboard/commit/50836dad7bf3d1cb2e4e74e3c1984bd5b40b0cfe, the issue is that the shortcut runner is running everything as if it were piped, while manually running the script in an interactive terminal allocates a tty 

so, this meant that cb "sees" that it's getting piped and thinks it should have run some action that didn't exist, so I just added the action into the relevant section

**Closed as completed by Slackadays** 2023-07-13 16:42 UTC
Labels: bug
