### ISSUE TITLE
remote vps cannot use cb

### ISSUE THREAD

**Issue by newyorkthink** [Slackadays/Clipboard#135] opened 2023-06-21 06:10 UTC
i vps is install libstdc++6

but cb is cannot run
![image](https://github.com/Slackadays/Clipboard/assets/87791643/7ef720c6-c5f7-489e-9103-66106dcca3c2)

**Comment by Slackadays** [comment] 2023-06-21 15:39
Dupe of #121

**Closed by Slackadays** 2023-06-21 15:39 UTC
Labels: bug
