### ISSUE TITLE
Screen Flicker On KDE Plasma Wayland - Possibly A Wayland Bug

### ISSUE THREAD

**Issue by dante-e-v** [Slackadays/Clipboard#190] opened 2024-04-20 18:38 UTC
**Describe the bug**
Using clipboard in KDE Plasma Wayland makes the screen start flickering. Every time it flickers input is stopped so no typing on a keyboard during it.

It also clears any right-click context menus and closes desktop edit mode.

For some reason it also makes it so I can't launch a new plasma session in a different tty. Specifically it gives an error of:

`*ERROR* Failed to open channel.`

**To Reproduce**

`$ cb copy "test"`

**Expected behavior**
I expected that things would run normally and not glitch out the entire session.

**Version**
I'm using CB 0.9.0.1-1 from the AUR with Arch Linux (Vanilla). I installed it with the AUR helper paru.

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [ ] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [ ] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [x] I'm using the latest commit/release (we only support the latest)
- [ ] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**
I made sure to check issues and haven't seen anything like this.

I'm not familiar with how to find any logs pertaining to clipboard so if there are any I can grab that might helpful to debug this please let me know.

Wayland logs might also be useful so please let me know which ones I should grab and post.

I'm doing all this in a virtual machine. I know Wayland has issues with virtual machines but I've not encountered a bug like this with anything else.

**Comment by jirutka** [comment] 2024-06-01 18:48
I’m experiencing the same bug on Alpine Linux v3.19 with Sway 1.8. What’s going on here?

**Comment by Yanislavcore** [comment] 2024-06-06 16:14
I have the same problem on my Fedora 40 with KDE Plasma 6 and Wayland.

If I launch "cb", it stays launched and never dies causing screen and focus flicker. 

```
➜  ~ killall cb
➜  ~ ps aux | rg "\s+cb"
➜  ~ cb
┏━━ All your clipboards with content ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ 0│ CLIPBOARD_NOGUI=1                                                                                                                                                                                                                 ┃
┗━━▌Text, Files, Directories,  Data ▐━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
➜  ~ ps aux | rg "\s+cb"
yanisla+  188861  0.0  0.0 243032  5404 ?        Ss   19:13   0:00 cb

```

**Comment by Mcrtin** [comment] 2024-09-21 13:25
Same problem on hyprland; run `cb` and the currently focused window starts to flicker.
When in fullscreen it goes back to a normal window; the interval is initially, after the first run of cb ca. 3 sec. when calling it more times the interval shortens.

**Comment by iFreilicht** [comment] 2024-09-22 01:41
Some problem in NixOS with KDE Plasma 6 and Wayland. As noted above, `CLIPBOARD_NOGUI=1` fixes this, but that's not a good solution, I use `cb` primarily **because** of the GUI integration.

**Comment by iFreilicht** [comment] 2024-09-25 22:08
I actually managed to fix it! 🥳  It took a long time to understand how Clipboard interacts with Wayland, but in the end the fix was relatively simple. If you are suffering from the same issue, please take the time to test the fix. See #203 for details on how to do that.

**Comment by Slackadays** [comment] 2024-10-19 00:52
Dupe of https://github.com/Slackadays/Clipboard/issues/171, we still need to fix Wayland though

**Closed by Slackadays** 2024-10-19 00:52 UTC
Labels: bug
